export interface ATEvent {
    target: string,
    eventId: string,
    atclid: string,
    clickId: string,
    clientId: string,
    eventName: string,
    eventTime: string,
    eventValue: string,
    currency: string,
    trackingGroup: string,
    link: string,
    brandName: string,
    transactionId: string,
    shippingPrice: string,
    taxPrice: string,
}